# Generated by Django 5.1.3 on 2024-11-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_pr_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pr_photo',
            field=models.FileField(upload_to='pr_photo/'),
        ),
    ]
